In [135]:
import cv2
import numpy as np

In [136]:
matrix = img=np.full((5,5),10).astype(np.float32)
matrix

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]], dtype=float32)

In [137]:
def gkern(l=5, sig=1.):
    """\
    creates gaussian kernel with side length `l` and a sigma of `sig`
    """
    ax = np.linspace(-(l - 1) / 2., (l - 1) / 2., l)
    gauss = np.exp(-0.5 * np.square(ax) / np.square(sig))
    kernel = np.outer(gauss, gauss)
    return kernel / np.sum(kernel)
kernel = gkern(5,0.75)

In [138]:
mat = np.full((5,5),10)
print(mat*kernel)

[[0.00231029 0.03324944 0.08087679 0.03324944 0.00231029]
 [0.03324944 0.47852321 1.16397203 0.47852321 0.03324944]
 [0.08087679 1.16397203 2.83127519 1.16397203 0.08087679]
 [0.03324944 0.47852321 1.16397203 0.47852321 0.03324944]
 [0.00231029 0.03324944 0.08087679 0.03324944 0.00231029]]
